services:
  # --- INFRAESTRUTURA DE REDE ---
  consul:
    image: hashicorp/consul:latest
    container_name: consul-local
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500" # UI e API do Consul
    networks:
      - lps_network_local

  traefik:
    image: traefik:v3.0
    container_name: traefik-local
    command:
      # 1. Define o EntryPoint principal (Gateway) na porta 8080 (INTERNA)
      - "--entrypoints.web.address=:8080"
      
      # 2. Habilita a API e o Dashboard (também na porta 8080 INTERNA)
      - "--api.insecure=true"
      - "--api.dashboard=true"

      # 3. Diz ao Traefik para buscar serviços no Consul
      - "--providers.consulcatalog.prefix=traefik"
      - "--providers.consulcatalog.endpoint.address=consul-local:8500"
    ports:
      # 4. Mapeia a porta 8888 (do SEU PC) para a porta 8080 (do container)
      - "8888:8080" # <-- SEU GATEWAY (API) VAI RODAR AQUI
      
      # 5. Mapeia a porta 8181 (do SEU PC) para a porta 8080 (do container)
      - "8181:8080" # <-- SEU DASHBOARD VAI RODAR AQUI
    depends_on:
      - consul
    networks:
      - lps_network_local

networks:
  lps_network_local:
    driver: bridge