services:
  # --- INFRAESTRUTURA DE REDE ---
  consul:
    image: hashicorp/consul:latest
    container_name: consul-local
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500" # UI e API do Consul
    networks:
      - lps_network_local

  traefik:
    image: traefik:v3.0
    container_name: traefik-local
    command:
      - "--entrypoints.web.address=:8080"
      - "--api.insecure=true"
      - "--entrypoints.dashboard.address=:8081"
      - "--api.dashboard=true"
      - "--providers.consulcatalog.prefix=traefik"
      - "--providers.consulcatalog.endpoint.address=consul-local:8500"
    ports:
      - "8888:8080"  # External API (web entrypoint)
      - "8181:8081"  # Dashboard
    depends_on:
      - consul
    networks:
      - lps_network_local
  # SERVIÇO DE PAGAMENTO
  ms-pagamento:
    build:
      context: ./backend/ms-pagamento
      dockerfile: Dockerfile
    image: ecommerce-spl/ms-pagamento
    container_name: ms-pagamento
    ports:
      - "8004:8004" # Porta interna:externa
    environment:
      # TRAEFIK Tags (para o Traefik rotear as requisições)
      - "TRAEFIK_TAGS=traefik.http.routers.ms-pagamento.rule=PathPrefix(`/api/pagamento`)"
    labels:
      # Configuração do Traefik para o serviço de pagamento
      - "traefik.enable=true"
      - "traefik.http.routers.ms-pagamento.rule=PathPrefix(`/api/pagamento`)"
      - "traefik.http.routers.ms-pagamento.entrypoints=web"
      - "traefik.http.services.ms-pagamento.loadbalancer.server.port=8004"
    networks:
      - lps_network_local 
    # A dependência do Consul garante que ele se registre no momento certo
    depends_on:
      - consul-local
  # SERVIÇO DE PEDIDOS
  ms-pedido:
    build:
      context: ./backend/ms-pedido
      dockerfile: Dockerfile
    image: ecommerce-spl/ms-pedido
    container_name: ms-pedido
    ports:
      - "8005:8005" # Porta interna:externa
    environment:
      # Variáveis de ambiente para comunicação interna
      - CARRINHO_SERVICE_URL=http://ms-carrinho:8002/api/carrinho
      - PAGAMENTO_SERVICE_URL=http://ms-pagamento:8004/api/pagamento
    labels:
      # Configuração do Traefik para o serviço de pedidos
      - "traefik.enable=true"
      - "traefik.http.routers.ms-pedido.rule=PathPrefix(`/api/pedido`)"
      - "traefik.http.routers.ms-pedido.entrypoints=web"
      - "traefik.http.services.ms-pedido.loadbalancer.server.port=8005"
    networks:
      - lps_network_local # Garantindo que está na mesma rede
    depends_on:
      - consul-local
      - ms-carrinho # Depende do carrinho e pagamento para a orquestração
      - ms-pagamento

networks:
  lps_network_local:
    driver: bridge