version: '3.9'

services:
  # 1. Service Registry
  consul:
    # ... (igual ao anterior)
    networks:
      - lps_network

  # 2. API Gateway
  traefik:
    # ... (igual ao anterior)
    networks:
      - lps_network

  # 3. O BANCO DE DADOS (NOVO!)
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogo_db
    ports:
      - "5432:5432" # Expõe a porta para o host (nosso app FastAPI)
    networks:
      - lps_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  lps_network:
    driver: bridge

volumes: # Volume para persistir os dados do DB
  postgres_data:
